[package]
name = "gui"
version = "0.1.0"
authors = ["Erlend Langseth <erlend.langseth@openanalytics.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input = { path = "../universe/crates/input"}

[dev-dependencies]
vxdraw = "0.5"
cgmath = "0.17.0"
